### ISSUE TITLE
Issue with two first points of grinding trajectory

### ISSUE THREAD

**Issue by Nandite** [InstitutMaupertuis/bezier#27]
![defect_first_normal](https://cloud.githubusercontent.com/assets/18351724/16581261/d0d18c8a-42a8-11e6-960a-4d609af4cf49.png)

@VictorLamoine 
@KevinBollore 
The two first points are too close or even mixed up

**Comment by VictorLamoine** [comment]
And the orientation looks wrong.
The second point should be filtered by `filterNeighborPosesTooClose`
