### ISSUE TITLE
Implement neighbor filtering 

### ISSUE THREAD

**Issue by VictorLamoine** [InstitutMaupertuis/bezier#5]
Some poses are generated very close to each other, we need to implement a filtering that reduces the number of points without affecting too much the trajectory precision

**Comment by Nandite** [comment]
I'll take it.

**Comment by Nandite** [comment]
Done ! Check the last pull request !

**Comment by VictorLamoine** [comment]
Re-opened because I reverted the commit: https://github.com/InstitutMaupertuis/bezier/pull/26

Please work on that again and test with every mesh in bezier_application.

**Comment by Nandite** [comment]
Ok got it !

**Comment by KevinBollore** [comment]
To my mind, this issue is ready to be closed.
